-- MySQL Script generated by MySQL Workbench
-- Mon Jan 12 10:49:41 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`uzytkownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`uzytkownik` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(128) NOT NULL,
  `haslo` BLOB(50) NOT NULL,
  `ip` VARBINARY(16) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iduzytkownik_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `ip_UNIQUE` (`ip` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`adres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adres` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rejon` VARCHAR(64) NOT NULL,
  `kod_pocztowy` SMALLINT(3) ZEROFILL UNSIGNED NOT NULL,
  `ulica` VARCHAR(64) NOT NULL,
  `numer_budynku` SMALLINT(255) NOT NULL,
  `numer_mieszkania` SMALLINT(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dane_uzytkownika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dane_uzytkownika` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(64) NOT NULL,
  `nazwisko` VARCHAR(64) NOT NULL,
  `numer_telefonu` VARCHAR(16) NOT NULL,
  `data_urodzenia` DATE NOT NULL,
  `data_smierci` DATE NULL,
  `adres_id` INT UNSIGNED NOT NULL,
  `uzytkownik_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_dane_uzytkownika_adres1_idx` (`adres_id` ASC) VISIBLE,
  INDEX `fk_dane_uzytkownika_uzytkownik1_idx` (`uzytkownik_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rodzina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rodzina` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(128) NOT NULL,
  `opis` VARCHAR(1024) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`obrazek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`obrazek` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tekst_alternatywny` VARCHAR(128) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modlitwa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modlitwa` (
  `id` SMALLINT(255) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(128) NULL,
  `tresc` VARCHAR(2048) NOT NULL,
  `efekt` VARCHAR(128) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proboszcz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proboszcz` (
  `id` TINYINT(255) UNSIGNED NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(64) NOT NULL,
  `nazwisko` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`parafia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`parafia` (
  `id` SMALLINT(255) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(256) NOT NULL,
  `proboszcz_id` TINYINT(255) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `proboszcz_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_parafia_proboszcz1_idx` (`proboszcz_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`opis_uzytkownika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`opis_uzytkownika` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uzytkownik_id` INT UNSIGNED NOT NULL,
  `plec` CHAR(1) NULL,
  `pseudonim` VARCHAR(64) NULL,
  `opis` VARCHAR(1024) NULL,
  `rodzina_id` INT UNSIGNED NOT NULL,
  `zdjecie_profilowe_id` INT UNSIGNED NOT NULL,
  `ulubiona_modlitwa_id` SMALLINT(255) UNSIGNED NOT NULL,
  `parafia_id` SMALLINT(255) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `rodzina_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_opis_uzytkownika_rodzina1_idx` (`rodzina_id` ASC) VISIBLE,
  INDEX `fk_opis_uzytkownika_obrazek1_idx` (`zdjecie_profilowe_id` ASC) VISIBLE,
  INDEX `fk_opis_uzytkownika_modlitwa1_idx` (`ulubiona_modlitwa_id` ASC) VISIBLE,
  INDEX `fk_opis_uzytkownika_parafia1_idx` (`parafia_id` ASC) VISIBLE,
  INDEX `fk_opis_uzytkownika_uzytkownik1_idx` (`uzytkownik_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pokrewienstwo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pokrewienstwo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `typ_relacji` ENUM('mama', 'ojciec', 'córka', 'syn', 'siostra', 'brat', 'ciotka', 'wujek', 'siostrzenica', 'bratanica', 'siostrzeniec', 'bratanek', 'kuzyn', 'kuzynka', 'babcia', 'dziadek', 'wnuczka', 'wnuk', 'rodzeństwo', 'rodzic', 'ojczym', 'macocha', 'pasierb', 'pasierbica', 'szwagier', 'szwagierka', 'teść', 'tesciowa', 'ziec', 'synowa') NOT NULL,
  `widzi_dane_osobowe` TINYINT NULL,
  `spokrewiniony_uzytkownik_id` INT UNSIGNED NOT NULL,
  `uzytkownik_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `spokrewiniony_uzytkownik_id`, `uzytkownik_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_pokrewienstwo_uzytkownik2_idx` (`spokrewiniony_uzytkownik_id` ASC) VISIBLE,
  INDEX `fk_pokrewienstwo_uzytkownik1_idx` (`uzytkownik_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tablica_ogloszeniowa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tablica_ogloszeniowa` (
  `id` SMALLINT(255) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(256) NOT NULL,
  `opis` VARCHAR(2048) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ogloszenie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ogloszenie` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tytul` VARCHAR(128) NOT NULL,
  `data_wstawienia` DATE NOT NULL,
  `tresc` VARCHAR(512) NOT NULL,
  `tablica_ogloszeniowa_id` SMALLINT(255) UNSIGNED NOT NULL,
  `obrazek_id` INT UNSIGNED NOT NULL,
  `autor_id` INT UNSIGNED NOT NULL,
  `archiwalny` TINYINT NULL,
  PRIMARY KEY (`id`, `tablica_ogloszeniowa_id`, `autor_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_ogloszenie_tablica_ogloszeniowa1_idx` (`tablica_ogloszeniowa_id` ASC) VISIBLE,
  INDEX `fk_ogloszenie_obrazek1_idx` (`obrazek_id` ASC) VISIBLE,
  INDEX `fk_ogloszenie_uzytkownik1_idx` (`autor_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`uprawnienia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`uprawnienia` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rola` ENUM('zarządzanie użytkownikami', 'kreator postów', 'moderator postów', 'obserwator postów') NOT NULL,
  `tablica_ogloszeniowa_id` SMALLINT(255) UNSIGNED NOT NULL,
  `uzytkownik_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `tablica_ogloszeniowa_id`, `uzytkownik_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_uprawnienia_tablica_ogloszeniowa1_idx` (`tablica_ogloszeniowa_id` ASC) VISIBLE,
  INDEX `fk_uprawnienia_uzytkownik1_idx` (`uzytkownik_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tablica_ogloszeniowa_uzytkownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tablica_ogloszeniowa_uzytkownik` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uzytkownik_id` INT UNSIGNED NOT NULL,
  `tablica_ogloszeniowa_id` SMALLINT(255) UNSIGNED NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`, `uzytkownik_id`, `tablica_ogloszeniowa_id`),
  INDEX `fk_tablica_ogloszeniowa_uzytkownik_uzytkownik1_idx` (`uzytkownik_id` ASC) VISIBLE,
  INDEX `fk_tablica_ogloszeniowa_uzytkownik_tablica_ogloszeniowa1_idx` (`tablica_ogloszeniowa_id` ASC) VISIBLE)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`wiek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`wiek` (`dane_uzytkownika_id` INT, `wiek` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`plodnosc_kreatorow_postow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plodnosc_kreatorow_postow` (`pseudonim` INT, `liczba_postow` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`rodzina_wzeniona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rodzina_wzeniona` (`rodzina_id` INT, `uzytkownik_id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`plodnosc_tablicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plodnosc_tablicy` (`id` INT, `nazwa` INT, `liczba_uzytkownikow` INT, `liczba_postow` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`pozycja_parafii`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pozycja_parafii` (`id` INT, `nazwa` INT, `liczba_wiernych` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`pozycja_modlitwy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pozycja_modlitwy` (`id` INT, `nazwa` INT, `liczba_polubien` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`pozycja_rodziny`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pozycja_rodziny` (`id` INT, `nazwa` INT, `liczba_czlonkow` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`matuzal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`matuzal` (`id` INT, `pseudonim` INT, `wiek` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`url_obrazka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`url_obrazka` (`obrazek_id` INT, `url` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`zmora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zmora` (`id` INT, `pseudonim` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`zmarly_uzytkownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zmarly_uzytkownik` (`id` INT, `pseudonim` INT, `data_smierci` INT);

-- -----------------------------------------------------
-- View `mydb`.`wiek`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`wiek`;
USE `mydb`;
CREATE  OR REPLACE VIEW wiek AS
SELECT dane_uzytkownika.id dane_uzytkownika_id, 
CASE
    WHEN data_smierci IS NULL THEN TIMESTAMPDIFF(YEAR, dane_uzytkownika.data_urodzenia, CURDATE())
    ELSE TIMESTAMPDIFF(YEAR, dane_uzytkownika.data_urodzenia, dane_uzytkownika.data_smierci)
END wiek
FROM dane_uzytkownika;

-- -----------------------------------------------------
-- View `mydb`.`plodnosc_kreatorow_postow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`plodnosc_kreatorow_postow`;
USE `mydb`;
CREATE  OR REPLACE VIEW plodnosc_kreatorow_postow AS 
SELECT ou.pseudonim, 
COUNT(o.id) AS liczba_postow 
FROM uzytkownik u 
JOIN opis_uzytkownika ou ON ou.id = u.id 
JOIN ogloszenie o ON o.autor_id = u.id GROUP BY u.id 
ORDER BY liczba_postow DESC LIMIT 10;

-- -----------------------------------------------------
-- View `mydb`.`rodzina_wzeniona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rodzina_wzeniona`;
USE `mydb`;
CREATE  OR REPLACE VIEW rodzina_wzeniona AS 
SELECT o.rodzina_id rodzina_id, u.id uzytkownik_id
FROM uzytkownik u
JOIN pokrewienstwo p ON p.uzytkownik_id = u.id
JOIN uzytkownik wspolmalzonek ON wspolmalzonek.id = p.spokrewiony_uzytkownik_id
JOIN opis_uzytkownika o ON o.id = wspolmalzonek.opis_uzytkownika_id
WHERE p.typ_relacji IN ('mąż', 'żona');

-- -----------------------------------------------------
-- View `mydb`.`plodnosc_tablicy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`plodnosc_tablicy`;
USE `mydb`;
CREATE  OR REPLACE VIEW plodnosc_tablicy AS
SELECT t.id, t.nazwa, 
COUNT(DISTINCT(tou.uzytkownik_id)) AS liczba_uzytkownikow, 
COUNT(DISTINCT(o.id)) AS liczba_postow FROM tablica_ogloszeniowa t 
LEFT JOIN tablica_ogloszeniowa_uzytkownik tou ON t.id = tou.tablica_ogloszeniowa_id 
LEFT JOIN ogloszenie o ON o.tablica_ogloszeniowa_id = t.id 
GROUP BY t.id, t.nazwa 
ORDER BY liczba_uzytkownikow DESC;

-- -----------------------------------------------------
-- View `mydb`.`pozycja_parafii`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pozycja_parafii`;
USE `mydb`;
CREATE  OR REPLACE VIEW pozycja_parafii AS
SELECT parafia.id, parafia.nazwa, 
COUNT(opis_uzytkownika.id) AS liczba_wiernych
FROM parafia
JOIN opis_uzytkownika ON opis_uzytkownika.parafia_id = parafia.id
GROUP BY parafia.id  
ORDER BY `parafia`.`id` ASC;

-- -----------------------------------------------------
-- View `mydb`.`pozycja_modlitwy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pozycja_modlitwy`;
USE `mydb`;
CREATE  OR REPLACE VIEW pozycja_modlitwy AS 
SELECT modlitwa.id, modlitwa.nazwa, 
COUNT(opis_uzytkownika.id) AS liczba_polubien
FROM modlitwa
JOIN opis_uzytkownika ON opis_uzytkownika.ulubiona_modlitwa_id = modlitwa.id
GROUP BY modlitwa.id  
ORDER BY `modlitwa`.`id` ASC;

-- -----------------------------------------------------
-- View `mydb`.`pozycja_rodziny`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pozycja_rodziny`;
USE `mydb`;
CREATE  OR REPLACE VIEW pozycja_rodziny AS
SELECT rodzina.id, rodzina.nazwa, 
COUNT(opis_uzytkownika.id) AS liczba_czlonkow
FROM rodzina
JOIN opis_uzytkownika ON opis_uzytkownika.rodzina_id = rodzina.id
GROUP BY rodzina.id  
ORDER BY `rodzina`.`id` ASC;

-- -----------------------------------------------------
-- View `mydb`.`matuzal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`matuzal`;
USE `mydb`;
CREATE  OR REPLACE VIEW matuzal AS
SELECT uzytkownik.id, opis_uzytkownika.pseudonim, wiek.wiek
FROM uzytkownik
JOIN opis_uzytkownika ON opis_uzytkownika.id = uzytkownik.opis_uzytkownika_id
JOIN dane_uzytkownika ON dane_uzytkownika.id = uzytkownik.dane_uzytkownika_id
JOIN wiek ON wiek.dane_uzytkownika_id = dane_uzytkownika.id
ORDER BY wiek.wiek DESC;

-- -----------------------------------------------------
-- View `mydb`.`url_obrazka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`url_obrazka`;
USE `mydb`;
CREATE  OR REPLACE VIEW url_obrazka AS
SELECT obrazek.id obrazek_id, CONCAT(CONCAT('/img/', obrazek.id), '.jpg') url
FROM obrazek;

-- -----------------------------------------------------
-- View `mydb`.`zmora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`zmora`;
USE `mydb`;
CREATE  OR REPLACE VIEW zmora AS
SELECT uzytkownik.id, opis_uzytkownika.pseudonim
FROM uzytkownik
JOIN opis_uzytkownika ON opis_uzytkownika.id = uzytkownik.opis_uzytkownika_id
WHERE NOT EXISTS (SELECT 1 FROM tablica_ogloszeniowa_uzytkownik WHERE tablica_ogloszeniowa_uzytkownik.uzytkownik_id = uzytkownik.id AND tablica_ogloszeniowa_uzytkownik.tablica_ogloszeniowa_id = 1);

-- -----------------------------------------------------
-- View `mydb`.`zmarly_uzytkownik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`zmarly_uzytkownik`;
USE `mydb`;
CREATE  OR REPLACE VIEW zmarly_uzytkownik AS
SELECT uzytkownik.id, opis_uzytkownika.pseudonim, dane_uzytkownika.data_smierci
FROM uzytkownik
JOIN opis_uzytkownika ON opis_uzytkownika.id = uzytkownik.opis_uzytkownika_id
JOIN dane_uzytkownika ON dane_uzytkownika.id = uzytkownik.dane_uzytkownika_id
WHERE dane_uzytkownika.data_smierci IS NOT NULL
ORDER BY dane_uzytkownika.data_smierci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
