import re
from pathlib import Path


def normalize_numeric_types(sql: str) -> str:
    sql = re.sub(r"TINYINT\s*\(\s*\d+\s*\)", "TINYINT", sql, flags=re.I)
    #sql = re.sub(r"SMALLINT\s*\(\s*\d+\s*\)", "SMALLINT", sql, flags=re.I)
    sql = re.sub(r"INT\s*\(\s*\d+\s*\)", "INT", sql, flags=re.I)
    return sql


def remove_mysql_specific_syntax(sql: str) -> str:
    patterns = [
        (r"\s+VISIBLE", ""),
        (r"\s+INVISIBLE", ""),
        (r"\s+ASC", ""),
        (r"\)\s*ENGINE\s*=\s*InnoDB", ")"),
        (r"-- MySQL Script generated by MySQL Workbench.*?\n", ""),
        (r"-- MySQL Workbench Forward Engineering.*?\n", ""),
        (r"-- Model:.*?\n", ""),
    ]

    for pattern, repl in patterns:
        sql = re.sub(pattern, repl, sql, flags=re.I | re.S)

    return sql


def fix_auto_increment_primary_keys(sql: str) -> str:
    """
    AUTO_INCREMENT + złożony PK → PK(id) + UNIQUE(...)
    """
    def repl(match):
        column = match.group("col")
        rest = match.group("rest")
        return f"PRIMARY KEY ({column}), UNIQUE ({rest})"

    pattern = re.compile(
        r"PRIMARY KEY\s*\(\s*(?P<col>\w+)\s*,\s*(?P<rest>[^)]+)\)",
        flags=re.I
    )

    return pattern.sub(repl, sql)


# def ensure_foreign_key_checks(sql: str) -> str:
#     sql = sql.strip()

#     if not re.search(r"SET\s+FOREIGN_KEY_CHECKS\s*=\s*0", sql, re.I):
#         sql = "SET FOREIGN_KEY_CHECKS = 0;\n\n" + sql

#     if not re.search(r"SET\s+FOREIGN_KEY_CHECKS\s*=\s*1", sql, re.I):
#         sql = sql + "\n\nSET FOREIGN_KEY_CHECKS = 1;"

#     return sql


def convert_mysql_to_mariadb(sql: str) -> str:
    sql = remove_mysql_specific_syntax(sql)
    #sql = normalize_numeric_types(sql)
    sql = fix_auto_increment_primary_keys(sql)
    # sql = ensure_foreign_key_checks(sql)

    sql = re.sub(r"\n{3,}", "\n\n", sql)
    return sql.strip() + "\n"


def main():
    input_file = Path("pusta_baza_mysql.sql")
    output_file = Path("../1_pusta_baza_z_triggerami.sql")

    sql = input_file.read_text(encoding="utf-8")
    converted = convert_mysql_to_mariadb(sql)
    output_file.write_text(converted, encoding="utf-8")

    print("Konwersja zakończona.")


if __name__ == "__main__":
    main()